"""
masking/__init__.py

MH Masking package - Mask cropping, pasting, and boolean operations for ComfyUI.
"""

from .crop_and_paste import NODE_CLASS_MAPPINGS as CROP_MAPPINGS
from .crop_and_paste import NODE_DISPLAY_NAME_MAPPINGS as CROP_DISPLAY_MAPPINGS
from .mask_boolean import NODE_CLASS_MAPPINGS as BOOLEAN_MAPPINGS
from .mask_boolean import NODE_DISPLAY_NAME_MAPPINGS as BOOLEAN_DISPLAY_MAPPINGS
from .mask_minimal_crop import NODE_CLASS_MAPPINGS as MINIMAL_MAPPINGS
from .mask_minimal_crop import NODE_DISPLAY_NAME_MAPPINGS as MINIMAL_DISPLAY_MAPPINGS

# Aggregate all node mappings
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(CROP_MAPPINGS)
NODE_CLASS_MAPPINGS.update(BOOLEAN_MAPPINGS)
NODE_CLASS_MAPPINGS.update(MINIMAL_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(CROP_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(BOOLEAN_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(MINIMAL_DISPLAY_MAPPINGS)

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
]
